# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Distribute iOS App to Firebase"
  lane :distribute_ios_app do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      groups: "Testers",
      release_notes: ENV["COMMIT_MESSAGE"],
      ipa_path: "../build/ios/ipa/flutter_cicd.ipa",
      service_credentials_file: "firebase_credentials.json"
    )
  end
end
