# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def delete_temp_keychain(name)
    delete_keychain(
      name: name
    ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
    create_keychain(
      name: name,
      password: password,
      unlock: false,
      timeout: 0
    )
end

def ensure_temp_keychain(name, password)
    delete_temp_keychain(name)
    create_temp_keychain(name, password)
end

platform :ios do
  desc "Install certificate and profile"
  lane :install_certificate_and_profile do
    api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
        in_house: false,
    )

    keychain_name = "TEMP_KEYCHAIN_USER"
    keychain_password = ENV["TEMP_KEYCHAIN_PASSWORD"]
    ensure_temp_keychain(keychain_name, keychain_password)

    match(
        type: 'adhoc',
        app_identifier: "com.example.flutterCicdRino",
        git_basic_authorization: Base64.strict_encode64(ENV["REPO_AUTHORIZATION"]),
        keychain_name: keychain_name,
        keychain_password: keychain_password,
        api_key: api_key
    )
  end
  desc "Increse iOS build number"
  lane :increment_ios_build_number do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID_IOS"],
      service_credentials_file: "firebase_credentials.json"
    )
    increment_build_number({ 
      build_number: latest_release[:buildVersion].to_i + 1,
      xcodeproj: "./Runner.xcodeproj"
    })
  end
  desc "Distribute iOS App to Firebase"
  lane :distribute_ios_app do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      groups: "Testers",
      release_notes: ENV["COMMIT_MESSAGE"],
      ipa_path: "../build/ios/ipa/flutter_cicd.ipa",
      service_credentials_file: "firebase_credentials.json"
    )
  end
end
