# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Increse Android version code"
  lane :increment_android_version_code do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      service_credentials_file: "firebase_credentials.json"
    )
    if latest_release 
    new_version_code = latest_release[:buildVersion].to_i + 1
    increment_version_code({ version_code: new_version_code })
  end
  desc "Distribute Android App to Firebase"
  lane :distribute_android_app do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      groups: "Testers",
      release_notes: "Distribute Android App to Firebase",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: "firebase_credentials.json"
  )
  end
end
