name: Distribute android app to firebase
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  distribute_apk:
    runs-on: macos-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "8"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Android Gems
        working-directory: ${{ github.workspace }}/android
        run: bundle install
      - name: Flutter get
        working-directory: ${{ github.workspace }}
        run: flutter pub get
