name: Distribute android app to firebase
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_apk:
    runs-on: macos-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "8"
